version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - mqtt-network

  mqtt-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-server
    ports:
      - "3000:3000"
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
